# Replace “File” with the name of your Java file, sans any extensions. For example, if you were working with a Java file
# called, Assignment2.java, then replace “File” with “Assignment2”.
filename = SwitchExample__Ordering

all: compile run

compile:
	javac $(filename).java

run:
	java $(filename)

clean:
	rm $(filename).class
